/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author camil
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName());

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal(String nombre) { // <--- Agregamos String nombre aquí
        initComponents();

        // Ahora 'nombre' ya funciona porque viene desde el paréntesis
        lblUsuarioLogueado.setText("Usuario conectado: " + nombre);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        desktopContenedor = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblUsuarioLogueado = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPrincipal = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemCerrarSesion = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        menuOperaciones = new javax.swing.JMenu();
        itemRegistro = new javax.swing.JMenuItem();
        itemInventario = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblUsuarioLogueado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuarioLogueado.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarioLogueado.setText("Usuario: [Nombre]");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuarioLogueado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblUsuarioLogueado)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Fondo-MenuPrincipal.png"))); // NOI18N
        lblImagen.setText("jLabel1");

        desktopContenedor.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopContenedor.setLayer(lblImagen, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopContenedorLayout = new javax.swing.GroupLayout(desktopContenedor);
        desktopContenedor.setLayout(desktopContenedorLayout);
        desktopContenedorLayout.setHorizontalGroup(
            desktopContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, Short.MAX_VALUE)
        );
        desktopContenedorLayout.setVerticalGroup(
            desktopContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopContenedorLayout.createSequentialGroup()
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPrincipal.setText("Menú");
        menuPrincipal.add(jSeparator1);

        itemCerrarSesion.setText("Cerrar sesión");
        itemCerrarSesion.addActionListener(this::itemCerrarSesionActionPerformed);
        menuPrincipal.add(itemCerrarSesion);

        itemSalir.setText("Salir");
        itemSalir.addActionListener(this::itemSalirActionPerformed);
        menuPrincipal.add(itemSalir);

        jMenuBar1.add(menuPrincipal);

        menuOperaciones.setText("Operaciones");

        itemRegistro.setText("Registrar paquete");
        itemRegistro.addActionListener(this::itemRegistroActionPerformed);
        menuOperaciones.add(itemRegistro);

        itemInventario.setText("Ver inventario ");
        itemInventario.addActionListener(this::itemInventarioActionPerformed);
        menuOperaciones.add(itemInventario);

        jMenuBar1.add(menuOperaciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopContenedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarSesionActionPerformed
        // TODO add your handling code here:
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que deseas cerrar la sesión?",
                "Cerrar Sesión",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            // 2. Crear una nueva instancia de tu ventana de Login
            // Asegúrate de que el nombre sea exactamente el de tu clase de Login
            FrmLogin login = new FrmLogin();

            // 3. Hacer visible el login
            login.setVisible(true);

            // 4. Cerrar (destruir) la ventana actual del Menú Principal
            this.dispose();
        }
    }//GEN-LAST:event_itemCerrarSesionActionPerformed

    private void itemRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistroActionPerformed
        // 1. Verificamos si la ventana ya está abierta para no duplicarla
        for (javax.swing.JInternalFrame frame : desktopContenedor.getAllFrames()) {
            if (frame instanceof VtnRegistroPaquetes) {
                frame.toFront(); // La trae al frente si ya existe
                return;
            }
        }

        // 2. Si no existe, la creamos
        VtnRegistroPaquetes ventana = new VtnRegistroPaquetes();
        desktopContenedor.add(ventana);

        // 3. Centrar la ventana en el panel
        int x = (desktopContenedor.getWidth() / 2) - (ventana.getWidth() / 2);
        int y = (desktopContenedor.getHeight() / 2) - (ventana.getHeight() / 2);
        ventana.setLocation(x, y);

        ventana.setVisible(true);
    }//GEN-LAST:event_itemRegistroActionPerformed

    private void itemInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInventarioActionPerformed
        // 1. Verificamos si ya está abierta
        for (javax.swing.JInternalFrame frame : desktopContenedor.getAllFrames()) {
            if (frame instanceof VtnInventario) {
                frame.toFront();
                return;
            }
        }

        VtnInventario vtn = new VtnInventario();
        desktopContenedor.add(vtn);

        // Centrar
        int x = (desktopContenedor.getWidth() / 2) - (vtn.getWidth() / 2);
        int y = (desktopContenedor.getHeight() / 2) - (vtn.getHeight() / 2);
        vtn.setLocation(x, y);

        vtn.setVisible(true);
    }//GEN-LAST:event_itemInventarioActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed

        // Preguntamos antes de cerrar para que no sea un accidente
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Desea cerrar la aplicación por completo?",
                "Confirmar salida",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0); // Esto mata el proceso del programa
        }
    }//GEN-LAST:event_itemSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuPrincipal("Admin").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopContenedor;
    private javax.swing.JMenuItem itemCerrarSesion;
    private javax.swing.JMenuItem itemInventario;
    private javax.swing.JMenuItem itemRegistro;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblUsuarioLogueado;
    private javax.swing.JMenu menuOperaciones;
    private javax.swing.JMenu menuPrincipal;
    // End of variables declaration//GEN-END:variables
}
