/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.PaqueteController;
import javax.swing.JOptionPane;

/**
 *
 * @author camil
 */
public class VtnActualizarEstado extends javax.swing.JInternalFrame {

    PaqueteController paqueteControl
            = new PaqueteController();

    /**
     * Creates new form VtnActualizarEstado
     */
    public VtnActualizarEstado() {
        initComponents();
        // Combo de estados
        cbNuevoEstado.setModel(
                new javax.swing.DefaultComboBoxModel<>(
                        new String[]{
                            "Seleccionar...",
                            "En Bodega",
                            "En Despacho",
                            "En Ruta",
                            "Entregado"
                        }
                )
        );

// Combo de ciudades
        cbNuevaUbicacion.setModel(
                new javax.swing.DefaultComboBoxModel<>(
                        new String[]{
                            "Seleccionar...",
                            "Armenia",
                            "Barranquilla",
                            "Bogotá",
                            "Bucaramanga",
                            "Cali",
                            "Cartagena",
                            "Cúcuta",
                            "Ibagué",
                            "Manizales",
                            "Medellín",
                            "Montería",
                            "Neiva",
                            "Pasto",
                            "Pereira",
                            "Popayán",
                            "Santa Marta",
                            "Sincelejo",
                            "Tunja",
                            "Valledupar",
                            "Villavicencio"
                        }
                )
        );
         limpiarCampos();
    }

    private void limpiarCampos() {
        txtGuia.setText("");
        cbNuevoEstado.setSelectedIndex(0);
        cbNuevaUbicacion.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtGuia = new javax.swing.JTextField();
        cbNuevaUbicacion = new javax.swing.JComboBox<>();
        cbNuevoEstado = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Actualización de Estado de Paquetes");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Actualización de Estado");

        txtGuia.setText("jTextField1");
        txtGuia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGuiaKeyReleased(evt);
            }
        });

        cbNuevaUbicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbNuevoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnActualizar.setBackground(new java.awt.Color(0, 153, 0));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Guia de paquete:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nuevo estado:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nueva ciudad:");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo.png"))); // NOI18N
        jLabel13.setText("jLabel5");

        jLabel12.setText("© 2026 GoPack | Todos los derechos reservados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(336, 336, 336))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbNuevoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbNuevaUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbNuevoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbNuevaUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113))
                    .addComponent(btnActualizar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        // Obtener datos
        String guia
                = txtGuia.getText().trim();

        String nuevoEstado
                = cbNuevoEstado.getSelectedItem().toString();

        String nuevaUbicacion
                = cbNuevaUbicacion.getSelectedItem().toString();

// Validaciones
        if (guia.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese una guía."
            );

            return;
        }

        if (nuevoEstado.equals("Seleccionar...")) {

            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un estado."
            );

            return;
        }

        if (nuevaUbicacion.equals("Seleccionar...")) {

            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione una ciudad."
            );

            return;
        }

// Actualizar en BD
        boolean actualizado
                = paqueteControl.actualizarEstadoPaquete(
                        guia,
                        nuevoEstado,
                        nuevaUbicacion
                );

// Resultado
        if (actualizado) {

            JOptionPane.showMessageDialog(
                    this,
                    "Estado actualizado correctamente."
            );

            limpiarCampos();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "No se encontró paquete con ésta guía."
            );
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtGuiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGuiaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuiaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<String> cbNuevaUbicacion;
    private javax.swing.JComboBox<String> cbNuevoEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtGuia;
    // End of variables declaration//GEN-END:variables
}
