/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import modelo.Paquete; 
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author camil
 */
public class VtnInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form VtnInventario
     */
    public VtnInventario() {
        initComponents();
        mostrarDatos(); // Esto cargará los paquetes registrados automáticamente
    }
    
    public void mostrarDatos() {
    // Definimos títulos de la tabla
    String[] titulos = {"Guía", "Remitente", "Destinatario", "Dirección", "Peso", "Tipo", "Estado", "Fecha"};
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
    
    try {
        // Conexión a la BD
        Connection con = conexion.ConexionBD.conectar();
        
        // Consulta SQL con las nuevas columnas que agregamos
        String sql = "SELECT * FROM paquetes";
        
        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Paquete p = new Paquete(
                rs.getString("guia_rastreo"),
                rs.getString("remitente"),
                rs.getString("destinatario"),
                rs.getString("direccion_entrega"),
                rs.getDouble("peso"),
                rs.getString("tipo_envio"),
                rs.getString("estado"),
                rs.getString("fecha_registro")
            );
            Object[] fila = new Object[] {
                p.getGuia(),
                p.getRemitente(), 
                p.getDestinatario(), 
                p.getDireccion(), 
                p.getPeso(), 
                p.getTipo(), 
                p.getEstado(), 
                p.getFecha()
            };
            
            modelo.addRow(fila);
        }
        
        tblInventario.setModel(modelo); // Asignamos los datos a tu tabla
        con.close();
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Inventario de Paquetes");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Inventario de Paquetes");

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Guía", "Remitente", "Destinatario", "Dirección", "Peso (Kg)", "Tipo", "Estado", "Fecha y Hora"
            }
        ));
        jScrollPane1.setViewportView(tblInventario);

        btnActualizar.setBackground(new java.awt.Color(51, 153, 0));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar Tabla");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(347, 347, 347))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        mostrarDatos(); // Simplemente vuelve a llamar a la función de carga
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInventario;
    // End of variables declaration//GEN-END:variables
}
