/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.PaqueteController;
import modelo.Paquete;
import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author camil
 */
public class VtnRastreo extends javax.swing.JInternalFrame {

    // Instancia del controlador para cumplir con MVC
    private PaqueteController control;

    /**
     * Creates new form VtnRastreo
     */
    public VtnRastreo() {
        initComponents();
        this.control = new PaqueteController();

        txtGuia.setText("");
        lblEstado.setText("Ingrese su guía para rastrear");
        progresoEnvio.setValue(0);

        // Detener el timer si se cierra la ventana
        this.addInternalFrameListener(new javax.swing.event.InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent e) {
                if (timerRastreo != null) {
                    timerRastreo.stop();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtGuia = new javax.swing.JTextField();
        btnRastrear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblEstado = new javax.swing.JLabel();
        progresoEnvio = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Rastreador de Pedidos");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Ingrese Número de Guía:");

        txtGuia.setText("jTextField1");

        btnRastrear.setBackground(new java.awt.Color(0, 153, 0));
        btnRastrear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRastrear.setForeground(new java.awt.Color(255, 255, 255));
        btnRastrear.setText("Rastrear");
        btnRastrear.addActionListener(this::btnRastrearActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Rastreo de Paquete");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado del Envío", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblEstado.setText("Estado del Envío");

        progresoEnvio.setStringPainted(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(progresoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEstado)
                .addGap(162, 162, 162))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(lblEstado)
                .addGap(29, 29, 29)
                .addComponent(progresoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jLabel4.setText("© 2026 GoPack | Todos los derechos reservados");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo.png"))); // NOI18N
        jLabel13.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 292, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(98, 98, 98)
                                        .addComponent(btnRastrear)))
                                .addGap(341, 341, 341))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(275, 275, 275))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRastrear))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRastrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRastrearActionPerformed
        String guiaIngresada = txtGuia.getText().trim();

        if (guiaIngresada.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número de guía.");
            return;
        }

        // 1. Si ya hay un timer corriendo de una búsqueda anterior, lo detenemos
        if (timerRastreo != null && timerRastreo.isRunning()) {
            timerRastreo.stop();
        }

        // 2. Buscamos el paquete por primera vez para validar si existe
        Paquete p = control.buscarPaquetePorGuia(guiaIngresada);

        if (p != null) {
            // 3. Creamos el Timer: se ejecutará cada 1000 milisegundos (1 segundo)
            timerRastreo = new javax.swing.Timer(1000, (e) -> {
                // Buscamos de nuevo (por si hubo cambios en BD) o usamos el objeto p
                // En este caso, recalculamos el estado con la fecha de registro original
                String estadoCalculado = control.calcularEstadoPorTiempo(p.getFechaSistema());

                // Actualizamos la interfaz
                lblEstado.setText(estadoCalculado);
                actualizarBarra(estadoCalculado);

                // 4. Si el paquete ya llegó a su destino, detenemos el reloj
                if (estadoCalculado.equals("ENTREGADO")) {
                    ((javax.swing.Timer) e.getSource()).stop();
                }
            });

            // 5. ¡Arrancamos el reloj!
            timerRastreo.start();

            // Llamada inicial para que no espere el primer segundo para mostrar algo
            lblEstado.setText(control.calcularEstadoPorTiempo(p.getFechaSistema()));
            actualizarBarra(lblEstado.getText());

        } else {
            lblEstado.setText("No encontrado");
            progresoEnvio.setValue(0);
            JOptionPane.showMessageDialog(this, "La guía '" + guiaIngresada + "' no existe.");
        }
    }//GEN-LAST:event_btnRastrearActionPerformed

    private void actualizarBarra(String estado) {
        switch (estado) {
            case "EN BODEGA": {
                progresoEnvio.setValue(25);
                progresoEnvio.setForeground(Color.BLACK);
            }
            case "EN DESPACHO": {
                progresoEnvio.setValue(50);
                progresoEnvio.setForeground(Color.BLACK);
            }
            case "EN RUTA": {
                progresoEnvio.setValue(75);
                progresoEnvio.setForeground(Color.BLACK);
            }
            case "ENTREGADO": {
                progresoEnvio.setValue(100);
                progresoEnvio.setForeground(Color.BLACK);
            }
        }
    }
    
    // <--- PÉGALO AQUÍ (Fuera del bloque de Variables declaration)
    private javax.swing.Timer timerRastreo;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRastrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JProgressBar progresoEnvio;
    private javax.swing.JTextField txtGuia;
    // End of variables declaration//GEN-END:variables
}
